FROM blitznote/debootstrap-amd64:16.04
#MAINTAINER clifton <cliftonk@gmail.com>

# install xvfb and other X dependencies for IB
RUN apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean \
    && apt-get update -y \
    && apt-get install -y xvfb libxrender1 libxtst6 x11vnc socat \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean

# install init scripts and binaries
ADD init/xvfb_init /etc/init.d/xvfb
ADD init/vnc_init /etc/init.d/vnc
ADD bin/xvfb-daemon-run /usr/bin/xvfb-daemon-run

RUN chmod 777 /etc/init.d/xvfb \
 && chmod 777 /etc/init.d/vnc \
 && chmod 777 /usr/bin/xvfb-daemon-run

# vnc (optional)
# set your own password to launch vnc
# ENV VNC_PASSWORD doughnuts

# 5900 for VNC
EXPOSE 5900

ENV DISPLAY :0